theme: jekyll-theme-slate
title: "<a href='/' >TBO Retro Page</a>"
description: "My Retro Collection"
url: "https://tboretro.github.io"

collections:
  home_computers:
    output: true
  ibm_compatibles:
    output: true
  ibm_portables:
    output: true
  game_consoles:
    output: true
  mobile_consoles:
    output: true  # Do not forget to add new collections to the defaults below!


defaults:
  - scope:
      path: ""      # site-wide
      type: "pages"
    values:
      layout: "tboretro"
  - scope:
      path: ""      # site-wide
      type: "home_computers"
    values:
      layout: "tboretro"
  - scope:
      path: ""      # site-wide
      type: "ibm_compatibles"
    values:
      layout: "tboretro"
  - scope:
      path: ""      # site-wide
      type: "ibm_portables"
    values:
      layout: "tboretro"             
  - scope:
      path: ""      # site-wide
      type: "game_consoles"
    values:
      layout: "tboretro"      
  - scope:
      path: ""      # site-wide
      type: "mobile_consoles"
    values:
      layout: "tboretro"            